import { ArrowSmallUpIcon } from "@heroicons/react/24/outline";
import Head from "next/head";
import Navbar from "@/components/Layout/Navbar";
import Footer from "@/components/Layout/Footer";
import Accueil from "@/components/Home/Accueil";
import Presentation from "@/components/Home/Presentation";
import FormationsExperiences from "@/components/Home/FormationsExperiences";
import Competences from "@/components/Home/Competences";
import Projets from "@/components/Home/Projets";
import Contact from "@/components/Home/Contact";

export default function Home() {
    return (
        <>
            <Head>
                <title>Portfolio de Louis JUIF</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link
                    rel="preconnect"
                    href="https://fonts.gstatic.com"
                    crossOrigin=""
                />
                <link
                    href="https://fonts.googleapis.com/css2?family=Neucha&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <Navbar />
            <main>
                <Accueil />
                <Presentation />
                <FormationsExperiences />
                <Competences />
                <Projets />
                <Contact />
                <a
                    href="#"
                    className="fixed bottom-6 md:bottom-10 right-6 md:right-10 p-3 text-stone-900 border-2 bg-white border-primary rounded-full hover:scale-110 transition-all"
                >
                    <ArrowSmallUpIcon className="w-8 h-8" />
                </a>
            </main>
            <Footer />
            <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
        </>
    );
}
